# Default values for flask-api-pizzaapp-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ""
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  secrets:
    FLASK_DB_USER: ""
    FLASK_DB_PASS: ""
  configMap:
    FLASK_ENV: ""
    FLASK_DB_TYPE: ""
    FLASK_DB_HOST: ""
    FLASK_DB_PORT: ""
    FLASK_DB_NAME: ""
    FLASK_JWT_SECRET: ""
    ENV_DETAILED_NAME: ""
    BANNER_COLOR: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  allowPrivilegeEscalation: false
  runAsUser: 20000
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

automountServiceAccountToken: false

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  host: ""
  tls:
    enabled: true
    secretName: "" 

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
