env:
  configMap:
    FLASK_ENV: "development"
    FLASK_DB_TYPE: "postgresql"
    FLASK_DB_HOST: "ep-long-frost-a8me8d2u-pooler.eastus2.azure.neon.tech"
    FLASK_DB_PORT: "5432"
    FLASK_DB_NAME: "pizzaapp-dev"
    # I know, I know...
    FLASK_JWT_SECRET: "test123test123"
    ENV_DETAILED_NAME: "dev-env"
    BANNER_COLOR: "yellow"

ingress:
  enabled: true
  className: nginx
  host: "" # Delivered by cli args
  path: /
  pathType: ImplementationSpecific
  tls:
    enabled: true
