env:
  configMap:
    FLASK_ENV: "development"
    FLASK_DB_TYPE: "postgresql"
    FLASK_DB_HOST: "kandula.db.elephantsql.com"
    FLASK_DB_PORT: "5432"
    FLASK_DB_NAME: "fnjewthn"
    FLASK_JWT_SECRET: "test123test123"
    ENV_DETAILED_NAME: "dev-env"
    BANNER_COLOR: "yellow"

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  host: "" # Delivered by cli args
  path: /
  pathType: ImplementationSpecific
  tls:
    enabled: true
