imagePullSecrets:
 - name: acr-registry-secret-prod-env

env:
  configMap:
    FLASK_ENV: "production"
    FLASK_DB_TYPE: "postgres"
    FLASK_DB_HOST: "kandula.db.elephantsql.com"
    FLASK_DB_PORT: "5432"
    FLASK_DB_NAME: "bpzdoeiq"
    FLASK_JWT_SECRET: "prod123prod123"
    ENV_DETAILED_NAME: "prod-env"
    BANNER_COLOR: ""
