env:
  configMap:
    FLASK_ENV: "development"
    FLASK_DB_TYPE: "postgres"
    FLASK_DB_HOST: "kandula.db.elephantsql.com"
    FLASK_DB_PORT: "5432"
    FLASK_DB_NAME: "amquuyng"
    FLASK_JWT_SECRET: "uat123uat123"
    ENV_DETAILED_NAME: "uat-env"
    BANNER_COLOR: "blue"
