apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-api-pizzaapp-chart.fullname" . }}
  labels:
    {{- include "flask-api-pizzaapp-chart.labels" . | nindent 4 }}
    {{- include "flask-api-pizzaapp-chart.versionLabel" (list . .Values.image.tag) | nindent 4 }}
data:
  {{- range $k, $v := .Values.env.configMap }}
    {{ $k }}: {{ $v | quote }}
  {{- end }}